#!/bin/sh
### BEGIN INIT INFO
# Provides: spacy
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: spaCy REST microservices
# Description: Start spaCy webservice.
### END INIT INFO
  
start () {
    echo -n "Starting spacy-services..."

    daemon --user spacy --respawn --command "python3 /usr/lib/python3/dist-packages/spacy-services/displacy/app.py" --name=spacy --verbose
    RETVAL=$?
    if [ $RETVAL = 0 ]
    then
        echo "done."
    else
        echo "failed. See error code for more information."
    fi
    return $RETVAL
}
 
stop () {
    # Stop daemon
    echo -n "Stopping spacy-services daemon..."
 
    daemon --stop --name=spacy --verbose
    RETVAL=$?
 
    if [ $RETVAL = 0 ]
    then
        echo "Done."
    else
        echo "Failed. See error code for more information."
    fi
    return $RETVAL
}
 
restart () {
    daemon --restart --name=spacy --verbose
}
 
status () {
    # Report on the status of the daemon
    daemon --running --verbose --name=spacy
    return $?
}
 
case "$1" in
    start)
        start
    ;;
    status)
        status
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    *)
        echo $"Usage: spacy {start|status|stop|restart}"
        exit 3
    ;;
esac
 
exit $RETVAL
