#!/bin/sh

# Upgrade pip if Linux release is Debian 10 (Debian Buster) so its Python package manager release too old to install spaCy
LINUX_RELEASE=`lsb_release --short --code`
if [[ "$LINUX_RELEASE" == "buster" ]]; then
    echo "Upgrade the old Python package manager pip3 of Debian Buster to newer pip release which can install spaCy"
    pip3 install --upgrade pip
fi

# install dependencies like SpaCy and language specific models
pip3 install -r /usr/lib/python3/dist-packages/spacy-services/displacy/requirements.txt

# daemon will run as separated user
adduser --system --disabled-password spacy

# load our additional systemd service config
systemctl daemon-reload

# start while booting
systemctl enable spacy

# (re)start after installation (or upgrade)
systemctl restart spacy
